; PlatformIO config para el blimp (XIAO ESP32S3)
; Basado en BlimpSwarm (github.com/LehighBlimpGroup/BlimpSwarm)

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    madhephaestus/ESP32Servo @ ^1.1.1
    https://github.com/bmellink/IBusBM.git
    adafruit/Adafruit BMP3XX Library @ ^2.1.4
    adafruit/Adafruit BusIO @ ^1.16.1
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    https://github.com/sparkfun/SparkFun_BNO08x_Arduino_Library.git

; La librería BlimpSwarm (act/, sense/, state/, comm/, robot/, util/)
; vive en lib/BlimpSwarm y PlatformIO la detecta automáticamente
; porque tiene su library.properties.

build_flags =
    -DCORE_DEBUG_LEVEL=1
